name: serverless meal planner with aws and openai

on:
  push:
    branches: [ main ]

      
  pull_request:
    branches: [ main ]


jobs:

  build-serverless-meal-planner:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Restore packages
      run: |
        cd src/backend \
         && npm install \

    - name: Build & Deploy serverless meal planner
      run: |
        cd infrastructure \
         && npm install \
         && npx cdk deploy --require-approval never \
          --context hostedZoneDomainName=inflow-it-labs.tk


          
